# yaml-language-server: $schema=./node_modules/harperdb/config-app.schema.json

rest: true

mqtt:
  network:
    port: 1883
  webSocket: true
  mTLS: false
  requireAuthentication: false

graphqlSchema:
  files: 'schemas/*.graphql'

jsResource:
  files: 'resources/*.ts'

static:
  files: 'web/*'
